default: &default
  adapter: postgresql
  timeout: 5000

development:
  <<: *default
  database: danbooru2
  username: danbooru
  host: postgres
  pool: 5

test:
  <<: *default
  database: danbooru2_test
  username: danbooru
  host: postgres
  pool: 5

<% if Rails.env.production? %>
production:
  <<: *default
  database: e621
  username: e621
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>
  pool: <%= Sidekiq.server? ? ENV.fetch("DB_WORKER_POOL_SIZE") : ENV.fetch("DB_POOL_SIZE") %>
<% end %>
